refactor: update icon references
ArkEcosystem/explorer pull request #1017
Opened 2021-12-09 16:00 UTC by leMaur

## Summary
https://app.clickup.com/t/1wu1hfn
waiting on https://github.com/ArkEcosystem/laravel-foundation/pull/95

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-01-13 10:59 UTC, ItsANameToo requested changes
- footer ark icon should be red as it was before
<img width="353" alt="image" src="https://user-images.githubusercontent.com/35610748/149317608-f00e02d8-def3-4229-a450-ddfb69c97e5d.png">

2022-01-13 11:10 UTC, ItsANameToo commented
@leMaur also conflicts

2022-01-13 11:24 UTC, leMaur commented
relies on https://github.com/ArkEcosystem/laravel-foundation/pull/221

2022-01-17 11:56 UTC, ItsANameToo approved these changes

2022-01-17 12:02 UTC, merged