fix: transaction details page sender and recipient responsiveness
ArkEcosystem/explorer pull request #363
Opened 2020-11-02 11:10 UTC by Highjhacker

## Summary

https://app.clickup.com/t/9rx4g6

Fix the Sender and Recipient fields responsiveness.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2020-11-02 14:08 UTC, samharperpittam approved these changes

2020-11-02 14:19 UTC, ItsANameToo requested changes
needs to work with addresses too, not just usernames + addresses

2020-11-03 08:55 UTC, ItsANameToo requested changes
mobile
<img width="47" alt="image" src="https://user-images.githubusercontent.com/35610748/97965327-793b8b00-1dba-11eb-9177-ad45fe24e700.png">

desktop
<img width="50" alt="image" src="https://user-images.githubusercontent.com/35610748/97965387-8fe1e200-1dba-11eb-829d-3c7359b85e96.png">

they sender / recipient aren't aligned with the other circles

2020-11-03 10:04 UTC, ItsANameToo approved these changes

2020-11-03 10:06 UTC, merged