refactor: delegate monitor responsiveness
ArkEcosystem/explorer pull request #423
Opened 2020-11-03 12:23 UTC by Highjhacker

## Summary

https://app.clickup.com/t/9wrp34

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2020-11-03 16:55 UTC, samharperpittam requested changes
A list of changes have been added to the task linked in the description.

2020-11-04 13:58 UTC, ItsANameToo requested changes

2020-11-04 15:57 UTC, samharperpittam approved these changes

2020-11-04 17:00 UTC, ItsANameToo requested changes

2020-11-05 14:46 UTC, ItsANameToo approved these changes

2020-11-05 14:57 UTC, merged