refactor: add Delegate avatar to the address details page
ArkEcosystem/explorer pull request #529
Opened 2020-11-06 14:53 UTC by Highjhacker

## Summary

https://app.clickup.com/t/a0vdkk

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2020-11-06 18:06 UTC, ItsANameToo submitted a review, later dismissed
see clickup comment from sammie

2020-11-09 11:44 UTC, samharperpittam requested changes
Looking better.

Final change request is to align the edge of the delegate avatar to the QR Code button similar to how the address avatar is on the left hand side.

![image](https://user-images.githubusercontent.com/44671015/98537251-e5b5fe80-2280-11eb-9acf-9f226a663ff4.png)


This needs to be changed on 768, 640 & 375

2020-11-09 13:06 UTC, samharperpittam approved these changes

2020-11-09 15:53 UTC, ItsANameToo approved these changes

2020-11-09 15:53 UTC, merged