feat: sticky table headers
ArkEcosystem/explorer pull request #703
Opened 2021-05-05 17:26 UTC by alfonsobries

## Summary

https://app.clickup.com/t/b8zjdr

- Now the table headers use a sticky position

Didn't find a specific design for the sticky headers so this branch should also needs design feedback, for now it looks like the screenshots:

Update:
- depends on https://github.com/ArkEcosystem/laravel-ui/pull/466
- Adjust the design of the tables
- make the skeleton responsive

https://user-images.githubusercontent.com/17262776/117183665-6a4f8880-ad9d-11eb-84eb-5b9fbb0e702f.mov

To test:
1. ensure to test in dark/light mode
2. on different screen sizes
3. on every table in the app

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-11 21:15 UTC, alexbarnsley requested changes
Looks good overall. The only thing I've noticed is the row hover underneath the sticky columns. Is a negative x margin doable to hide the edge of each row? 🤔 

![image](https://user-images.githubusercontent.com/8069294/117885486-d0f50a80-b2a5-11eb-8a05-b1a21c0d7f85.png)

![image](https://user-images.githubusercontent.com/8069294/117885806-36e19200-b2a6-11eb-9a22-0514947c5b01.png)

2021-05-13 10:28 UTC, alexbarnsley requested changes
@alfonsobries 2 things

# Column Border too wide

@alfonsobries grabbed the below from the styleguide - the hover needs to extend past the column border

![image](https://user-images.githubusercontent.com/8069294/118110540-6e515b00-b3da-11eb-8d46-86960f962583.png)

This is what it's doing at the moment (ignore the blue hover colour for now):

![image](https://user-images.githubusercontent.com/8069294/118110723-af496f80-b3da-11eb-8f96-5cabc62e19be.png)

# Sticky Column when changing pages

They disappear on page change

https://user-images.githubusercontent.com/8069294/118113318-0bfa5980-b3de-11eb-9858-7799b2dac02b.mov

2021-05-24 12:37 UTC, samharperpittam approved these changes

2021-05-25 09:21 UTC, ItsANameToo requested changes

2021-05-25 14:59 UTC, ItsANameToo approved these changes

2021-05-25 15:21 UTC, merged