refactor: alignment tweaks for the amount row on mobile tables
ArkEcosystem/explorer pull request #707
Opened 2021-05-07 14:41 UTC by Highjhacker

## Summary

https://app.clickup.com/t/jf2zyy

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2021-05-11 18:52 UTC, alexbarnsley requested changes
see above message

2021-05-13 09:47 UTC, samharperpittam approved these changes

2021-05-13 10:58 UTC, alexbarnsley requested changes
The Amount height is still 4px taller meaning the gap will be larger above Amount compared to below it (and other gaps) :watching:

![image](https://user-images.githubusercontent.com/8069294/118115421-d1de8700-b3e0-11eb-93b7-898e90f41b19.png)

![image](https://user-images.githubusercontent.com/8069294/118115454-dc991c00-b3e0-11eb-8639-765a51713796.png)

2021-05-25 10:43 UTC, ItsANameToo approved these changes

2021-05-25 10:44 UTC, alexbarnsley approved these changes

2021-05-25 10:44 UTC, merged