refactor: move search to navbar
ArkEcosystem/explorer pull request #718
Opened 2021-05-14 17:22 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/jd8772

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-17 11:15 UTC, samharperpittam requested changes
Looking at the designs, the width of the search box should be the same as the width of the content behind it.

Essentially, the box should have the same width as indicated by the red rectangle here:
![image](https://user-images.githubusercontent.com/44671015/118479864-6f032d80-b709-11eb-8329-7c84f3f6ae6c.png)

2021-05-17 11:34 UTC, samharperpittam requested changes
When the 'Advanced Search' is open, can we change the title of the button from `Hide Search` to `Hide Advanced`

I think that makes more sense seeing as clicking `Hide Search` doesn't actually hide the search, it just hides the Advanced options

![image](https://user-images.githubusercontent.com/44671015/118482077-2ac55c80-b70c-11eb-9753-ea5a891ddb52.png)

2021-05-17 15:28 UTC, samharperpittam approved these changes

2021-05-25 12:51 UTC, ItsANameToo requested changes

2021-05-26 13:34 UTC, ItsANameToo approved these changes

2021-05-27 07:21 UTC, merged