chore: dark error images
ArkEcosystem/explorer pull request #721
Opened 2021-05-18 02:01 UTC by alfonsobries

## Summary

Updates the error page with the dark-related classes and uses a dark image in case the user has the dark theme.

The easiest way to test is to open the `app/Http/Controllers/HomeController.php` and hardcoding something like `abort(404)`, `abort(500)`, etc. inside the __invoke method and open the home page.

Notice that the current 404 error page (if you visit any non-existent page) currently doesn't handle the dark theme. That problem is fixed [on this PR](https://github.com/ArkEcosystem/explorer.ark.io/pull/716), (you can test it with the abort(404) method)

Another note is that I didn't find a design for 500 error pages, so I left the one we have (see screenshots)

![image](https://user-images.githubusercontent.com/17262776/118578141-456df480-b751-11eb-8752-2fd6c09817b4.png)

![image](https://user-images.githubusercontent.com/17262776/118578180-51f24d00-b751-11eb-8ae6-ab3f3e85e7a1.png)

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-20 09:05 UTC, samharperpittam reviewed
@alfonsobries  - There is a `500` svg in the clickup task

Also, could you provide some more detail in where I'd hardcode the abort pages in `app/Http/Controllers/HomeController.php` so I can get this task cleared down. 

Thanks

2021-05-20 15:49 UTC, samharperpittam approved these changes

2021-05-24 14:07 UTC, alexbarnsley requested changes

2021-05-26 13:53 UTC, ItsANameToo requested changes
@alfonsobries two things:
- the 404 pages align differently between dark and light (see slack for vid)
- the text is still black in dark mode on the 404 page (but maybe this has to do with the session not being handled properly yet?). This is fine on the 500 page. Couldn't test other 4xx pages in dark mode as they all revert to light (also session?)

2021-05-26 14:24 UTC, closed without merging