feat: home page statistics box
ArkEcosystem/explorer pull request #724
Opened 2021-05-19 15:44 UTC by alfonsobries

## Summary

Depends on:
- https://github.com/ArkEcosystem/laravel-ui/pull/473
- https://app.clickup.com/t/jd87rd

Add the home page statistic box:

### To test

- You can set your `.env` settings  as `EXPLORER_NETWORK=production` and `EXPLORER_NETWORK=development` 
- Test dark mode and different screen sizes

Another points to focus on the test:
- That the statistics values are correct
- The refresh time/cache is what is expected, for example, the chart is updated every minute and values are cached maybe we want something more real-time so I leave that to your more experienced opinion.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-20 15:35 UTC, samharperpittam requested changes
Oh and one other small thing @alfonsobries 

The boxes currently use `rounded-lg` but they should be `rounded-xl`.

2021-05-24 08:32 UTC, samharperpittam approved these changes

2021-05-25 13:46 UTC, ItsANameToo requested changes
- my chart appears to not have proper borders 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/35610748/119507397-1a962880-bd6f-11eb-9868-da352281a0b2.png">

2021-05-25 19:36 UTC, alexbarnsley approved these changes

2021-05-26 12:43 UTC, ItsANameToo approved these changes

2021-05-26 12:43 UTC, merged