feat: adjust tabs design on homepage
ArkEcosystem/explorer pull request #726
Opened 2021-05-20 18:12 UTC by alfonsobries

## Summary

https://app.clickup.com/t/jt38jc

Moves the tabs  above the table like shown on the design and general refactoring

![image](https://user-images.githubusercontent.com/17262776/119028340-f69ca680-b96c-11eb-952e-27b23a21a58e.png)
![image](https://user-images.githubusercontent.com/17262776/119028365-fdc3b480-b96c-11eb-8e11-7e2b089b869e.png)

To test just compare the tabs with the design in different screen sizes and dark mode.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-21 09:09 UTC, samharperpittam approved these changes

2021-05-21 15:26 UTC, leMaur reviewed
`type filter` is visible for `latest blocks` on mobile. I think it should be hidden.

2021-05-25 14:30 UTC, ItsANameToo requested changes
can't seem to switch back to transactions after clicking the blocks tab, see video on slack

2021-05-26 13:04 UTC, ItsANameToo approved these changes

2021-05-26 13:19 UTC, merged