refactor: missing multipayment tooltip
ArkEcosystem/explorer pull request #842
Opened 2021-06-14 14:37 UTC by alfonsobries

## Checklist

https://app.clickup.com/t/m9but8

When viewing the amount of the multipayment wallet transactions, it filters the amount sent to itself and shows a tooltip with the amount.

Plus: updates the amount boxes padding to match the design, and now it shows the box on mobile (used to show only the amount)

### To test

1. Open a wallet (for example `/wallets/DArvWfH5nMDT38tWmo5k461vMQpRXHQWX9` and filter for multipayment transactions
2. See the tooltips
3. Check mobile, compact, and expanded tables, and dark mode

![image](https://user-images.githubusercontent.com/17262776/121722988-9ac8c780-caab-11eb-9912-6737805ee35d.png)
![image](https://user-images.githubusercontent.com/17262776/121723007-a0bea880-caab-11eb-91c2-2507c27b7e8e.png)
![image](https://user-images.githubusercontent.com/17262776/121723039-a9af7a00-caab-11eb-9969-e1ef0eb6ca85.png)

![image](https://user-images.githubusercontent.com/17262776/121722955-92708c80-caab-11eb-9d92-9ebd4d6c3c59.png)

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-06-14 16:50 UTC, alexbarnsley requested changes

2021-06-15 08:30 UTC, alexbarnsley approved these changes

2021-06-16 08:13 UTC, ItsANameToo requested changes
- when switching to the 'incoming' tab on a wallet, it ends up showing 2 tooltips
![image](https://user-images.githubusercontent.com/35610748/122182116-45652f80-ce8a-11eb-8cb5-2ed0ad964667.png)

- in the incoming tab, it has the amount styled as if it's an outgoing transaction while it should show it as an incoming one similar to mainnet explorer:
![image](https://user-images.githubusercontent.com/35610748/122182259-67f74880-ce8a-11eb-8e43-aafe76f75f4a.png)

- on the `all` tab it should show the calculated value (sent - received by the address itself), but on the `outgoing` tab it should only show the amount that's sent and on the `incoming` tab only the amount that's received. See how it switches between tabs on https://explorer.ark.io/wallets/ATK14wxyYxbELq2b91bAfBY8Vmh9J6MDej

2021-06-17 09:42 UTC, ItsANameToo requested changes
![image](https://user-images.githubusercontent.com/35610748/122372381-e9b9a580-cf60-11eb-8be5-2fdc5060a381.png)

one remaining issue, see above. Happens when switching between tabs (all -> incoming -> all)

other than that it looks good @alfonsobries :oleglala:

2021-06-18 15:58 UTC, ItsANameToo approved these changes

2021-06-22 08:02 UTC, merged