fix: use overflow to prevent gap in headers
ArkEcosystem/explorer pull request #906
Opened 2021-08-30 21:30 UTC by alfonsobries

## Summary

https://app.clickup.com/t/rvqzgz

Toved the border to the inner elements to prevent the gap

To test: open delegate, transactions, and blocks pages and ensure the error was fixed and the patch didn't cause any side effect

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-08-31 22:26 UTC, alexbarnsley requested changes
I believe this was tried before. An `overflow-hidden` doesn't work here because we show elements within the header. Steps:

- Go to a normal Wallet page (e.g. http://test-explorer.test/wallets/DEmuBPmAi4BY3VfKdZG8jgRdFsrEod34Y6)
- Click on the "Public Key" button
- Popup will open out of bounds

![image](https://user-images.githubusercontent.com/8069294/131583542-c9593aa1-99b0-4d6b-ab0d-17839654b625.png)

2021-09-01 15:21 UTC, alfonsobries commented
@alexbarnsley find another alternative ✅

2021-09-01 19:11 UTC, alexbarnsley approved these changes
Looks good @alfonsobries 👍

2021-09-03 14:52 UTC, ItsANameToo approved these changes

2021-09-03 14:52 UTC, merged