chore: clean up SVGs to prevent clashes
ArkEcosystem/explorer pull request #989
Opened 2021-10-26 13:35 UTC by Highjhacker

## Summary

https://app.clickup.com/t/1p0dhxc

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2021-10-26 13:51 UTC, leMaur requested changes

2021-10-26 13:51 UTC, leMaur commented on resources/icons/monitor.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><style>.monitor-st0{fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}</style><path class="monitor-st
`.monitor-st0` 👀

2021-10-26 13:51 UTC, leMaur commented on resources/icons/price.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><style>.price-st0{fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}</style><path class="price-st0" d
`.price-st0` 👀

2021-10-26 13:51 UTC, leMaur commented on resources/icons/transaction.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><style>.transaction-st0{fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round}</style><path class="transaction-st0" d="M6.7 2.9
`.transaction-st0` 👀

2021-10-26 13:51 UTC, leMaur commented on resources/icons/transactions.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><style>.transactions-st0{fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}</style><path class="trans
`.transaction-st0` 👀

2021-10-27 11:58 UTC, leMaur commented
@Highjhacker if you have checked that the design of each icon is unchanged... then the optimizations are ok for me! 🚀

2021-10-28 08:11 UTC, ItsANameToo approved these changes

2021-10-28 08:12 UTC, ItsANameToo commented
@Highjhacker conflict

2021-10-28 09:03 UTC, ItsANameToo approved these changes

2021-10-28 09:04 UTC, merged